# Generated by Django 3.1.1 on 2020-09-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=50)),
                ('subheading', models.CharField(max_length=50)),
                ('discription', models.CharField(max_length=250)),
            ],
        ),
    ]
